import "@/styles/globals.css";
import { Providers } from "@/providers/provider";
import { montserrat } from "@/components/fonts";

export const metadata = {
  title: "The Project Gameplan",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
