import "@/styles/globals.css";
import { Providers } from "@/providers/provider";
import TopNav from "@/components/client/navigation/nav";


// export const metadata = {
//   title: "The Project Gameplan",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
      <section >
        <TopNav />
        {children}
      </section>
  );
}
